package com.guyuan.dear.db;

import com.guyuan.dear.db.entities.GroupJoinUserEntity;
import com.guyuan.dear.db.entities.LocationEntity;
import com.guyuan.dear.db.entities.MeetingEntity;
import com.guyuan.dear.db.entities.MeetingsJoinUsersEntity;
import com.guyuan.dear.db.entities.SearchEntity;
import com.guyuan.dear.db.entities.StaffAttendanceEntity;
import com.guyuan.dear.db.entities.StaffEntity;
import com.guyuan.dear.db.entities.StaffsJoinLocationsEntity;
import com.guyuan.dear.db.entities.UserEntity;
import com.guyuan.dear.db.entities.UserGroupEntity;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig groupJoinUserEntityDaoConfig;
    private final DaoConfig locationEntityDaoConfig;
    private final DaoConfig meetingEntityDaoConfig;
    private final DaoConfig meetingsJoinUsersEntityDaoConfig;
    private final DaoConfig searchEntityDaoConfig;
    private final DaoConfig staffAttendanceEntityDaoConfig;
    private final DaoConfig staffEntityDaoConfig;
    private final DaoConfig staffsJoinLocationsEntityDaoConfig;
    private final DaoConfig userEntityDaoConfig;
    private final DaoConfig userGroupEntityDaoConfig;

    private final GroupJoinUserEntityDao groupJoinUserEntityDao;
    private final LocationEntityDao locationEntityDao;
    private final MeetingEntityDao meetingEntityDao;
    private final MeetingsJoinUsersEntityDao meetingsJoinUsersEntityDao;
    private final SearchEntityDao searchEntityDao;
    private final StaffAttendanceEntityDao staffAttendanceEntityDao;
    private final StaffEntityDao staffEntityDao;
    private final StaffsJoinLocationsEntityDao staffsJoinLocationsEntityDao;
    private final UserEntityDao userEntityDao;
    private final UserGroupEntityDao userGroupEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        groupJoinUserEntityDaoConfig = daoConfigMap.get(GroupJoinUserEntityDao.class).clone();
        groupJoinUserEntityDaoConfig.initIdentityScope(type);

        locationEntityDaoConfig = daoConfigMap.get(LocationEntityDao.class).clone();
        locationEntityDaoConfig.initIdentityScope(type);

        meetingEntityDaoConfig = daoConfigMap.get(MeetingEntityDao.class).clone();
        meetingEntityDaoConfig.initIdentityScope(type);

        meetingsJoinUsersEntityDaoConfig = daoConfigMap.get(MeetingsJoinUsersEntityDao.class).clone();
        meetingsJoinUsersEntityDaoConfig.initIdentityScope(type);

        searchEntityDaoConfig = daoConfigMap.get(SearchEntityDao.class).clone();
        searchEntityDaoConfig.initIdentityScope(type);

        staffAttendanceEntityDaoConfig = daoConfigMap.get(StaffAttendanceEntityDao.class).clone();
        staffAttendanceEntityDaoConfig.initIdentityScope(type);

        staffEntityDaoConfig = daoConfigMap.get(StaffEntityDao.class).clone();
        staffEntityDaoConfig.initIdentityScope(type);

        staffsJoinLocationsEntityDaoConfig = daoConfigMap.get(StaffsJoinLocationsEntityDao.class).clone();
        staffsJoinLocationsEntityDaoConfig.initIdentityScope(type);

        userEntityDaoConfig = daoConfigMap.get(UserEntityDao.class).clone();
        userEntityDaoConfig.initIdentityScope(type);

        userGroupEntityDaoConfig = daoConfigMap.get(UserGroupEntityDao.class).clone();
        userGroupEntityDaoConfig.initIdentityScope(type);

        groupJoinUserEntityDao = new GroupJoinUserEntityDao(groupJoinUserEntityDaoConfig, this);
        locationEntityDao = new LocationEntityDao(locationEntityDaoConfig, this);
        meetingEntityDao = new MeetingEntityDao(meetingEntityDaoConfig, this);
        meetingsJoinUsersEntityDao = new MeetingsJoinUsersEntityDao(meetingsJoinUsersEntityDaoConfig, this);
        searchEntityDao = new SearchEntityDao(searchEntityDaoConfig, this);
        staffAttendanceEntityDao = new StaffAttendanceEntityDao(staffAttendanceEntityDaoConfig, this);
        staffEntityDao = new StaffEntityDao(staffEntityDaoConfig, this);
        staffsJoinLocationsEntityDao = new StaffsJoinLocationsEntityDao(staffsJoinLocationsEntityDaoConfig, this);
        userEntityDao = new UserEntityDao(userEntityDaoConfig, this);
        userGroupEntityDao = new UserGroupEntityDao(userGroupEntityDaoConfig, this);

        registerDao(GroupJoinUserEntity.class, groupJoinUserEntityDao);
        registerDao(LocationEntity.class, locationEntityDao);
        registerDao(MeetingEntity.class, meetingEntityDao);
        registerDao(MeetingsJoinUsersEntity.class, meetingsJoinUsersEntityDao);
        registerDao(SearchEntity.class, searchEntityDao);
        registerDao(StaffAttendanceEntity.class, staffAttendanceEntityDao);
        registerDao(StaffEntity.class, staffEntityDao);
        registerDao(StaffsJoinLocationsEntity.class, staffsJoinLocationsEntityDao);
        registerDao(UserEntity.class, userEntityDao);
        registerDao(UserGroupEntity.class, userGroupEntityDao);
    }
    
    public void clear() {
        groupJoinUserEntityDaoConfig.clearIdentityScope();
        locationEntityDaoConfig.clearIdentityScope();
        meetingEntityDaoConfig.clearIdentityScope();
        meetingsJoinUsersEntityDaoConfig.clearIdentityScope();
        searchEntityDaoConfig.clearIdentityScope();
        staffAttendanceEntityDaoConfig.clearIdentityScope();
        staffEntityDaoConfig.clearIdentityScope();
        staffsJoinLocationsEntityDaoConfig.clearIdentityScope();
        userEntityDaoConfig.clearIdentityScope();
        userGroupEntityDaoConfig.clearIdentityScope();
    }

    public GroupJoinUserEntityDao getGroupJoinUserEntityDao() {
        return groupJoinUserEntityDao;
    }

    public LocationEntityDao getLocationEntityDao() {
        return locationEntityDao;
    }

    public MeetingEntityDao getMeetingEntityDao() {
        return meetingEntityDao;
    }

    public MeetingsJoinUsersEntityDao getMeetingsJoinUsersEntityDao() {
        return meetingsJoinUsersEntityDao;
    }

    public SearchEntityDao getSearchEntityDao() {
        return searchEntityDao;
    }

    public StaffAttendanceEntityDao getStaffAttendanceEntityDao() {
        return staffAttendanceEntityDao;
    }

    public StaffEntityDao getStaffEntityDao() {
        return staffEntityDao;
    }

    public StaffsJoinLocationsEntityDao getStaffsJoinLocationsEntityDao() {
        return staffsJoinLocationsEntityDao;
    }

    public UserEntityDao getUserEntityDao() {
        return userEntityDao;
    }

    public UserGroupEntityDao getUserGroupEntityDao() {
        return userGroupEntityDao;
    }

}
